### ISSUE TITLE
Mise en cache des données de production avant processing

### ISSUE THREAD

**Issue by edaubert** [139bercy/decp-augmente#19]
Actuellement dans chaque PR, la CI télécharge l'ensemble des données à utiliser pour construire les données finaux qui seront envoyé à la production.

Peut-être pourrions nous tirer partie du cache CircleCi pour télécharger avec un cron ces données et ainsi y avoir accès beaucoup plus rapidement dans la CI.

@strainel @desrousseaux Qu'en pensez-vous ?

L'inconvénient c'est que l'on met des données potentiellement sensible dans un cache externe au ministère.
Pour autant même si les données ne sont pas dans le cache actuellement, elles sont tout de même sur des serveurs externes au ministères.

**Comment by desrousseaux** [comment]
C'est une excellente idée. Pas de soucis de confidentialité, tout est en open data.

**Comment by edaubert** [comment]
Gérer avec https://github.com/139bercy/decp-augmente/pull/18
